title: "Examples of book contents"
author: Pawel Kaminski
copyright: "2024"

repository:
  url: https://github.com/kaminski-pawel/book-content-examples
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

execute:
  execute_notebooks: off
